//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// TEXCOORD                 1   xyz         2     NONE   float       
// TEXCOORD                 2   xyz         3     NONE   float       
// COLOR                    0   xyzw        4     NONE   float      w
// TEXCOORD                 4   xyzw        5     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[19], immediateIndexed
dcl_constantbuffer CB1[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps linear v1.xy
dcl_input_ps linear v4.w
dcl_output o0.xyzw
dcl_temps 2
mad r0.xy, v1.xyxx, cb0[16].xyxx, cb0[16].zwzz
mad r0.xy, cb1[0].yyyy, cb0[15].zwzz, r0.xyxx
sample r0.xyzw, r0.xyxx, t3.xyzw, s3
add r0.y, v4.w, cb0[15].x
add r0.x, -r0.y, r0.x
div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[15].y
mul_sat r0.x, r0.y, r0.x
mad r0.y, r0.x, l(-2.000000), l(3.000000)
mul r0.x, r0.x, r0.x
mad r0.x, -r0.y, r0.x, l(1.000000)
max r0.x, r0.x, l(0.000000)
mad r0.yz, v1.xxyx, cb0[7].xxyx, cb0[7].zzwz
add r0.yz, r0.yyzy, r0.yyzy
mad r0.yz, cb1[0].yyyy, cb0[8].xxyx, r0.yyzy
sample r1.xyzw, r0.yzyy, t0.xyzw, s1
mad r0.yz, v1.xxyx, cb0[10].xxyx, cb0[10].zzwz
mad r0.yz, cb1[0].yyyy, cb0[9].xxyx, r0.yyzy
mad r0.yz, r1.xxxx, cb0[8].zzzz, r0.yyzy
sample r1.xyzw, r0.yzyy, t1.xyzw, s0
mul r0.x, r0.x, r1.w
mul r0.x, r0.x, cb0[11].w
mul r0.x, r0.x, cb0[17].x
mad r0.yz, v1.xxyx, cb0[18].xxyx, cb0[18].zzwz
sample r1.xyzw, r0.yzyy, t4.xyzw, s4
mul r0.x, r0.x, r1.w
mad r0.yz, v1.xxyx, cb0[13].xxyx, cb0[13].zzwz
mad r0.yz, cb1[0].yyyy, cb0[12].yyzy, r0.yyzy
sample r1.xyzw, r0.yzyy, t2.xyzw, s2
mul_sat r0.x, r0.x, r1.w
mul o0.w, r0.x, v4.w
mov o0.xyz, l(0,0,0,0)
ret 
// Approximately 0 instruction slots used
