//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 0   xy          2     NONE   float   xy  
// TEXCOORD                 1   xyzw        3     NONE   float       
// TEXCOORD                 2   xyzw        4     NONE   float       
// TEXCOORD                 3   xyzw        5     NONE   float       
// TEXCOORD                 4   xyzw        6     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[12], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_temps 4
mul r0.xyzw, cb0[11].zzzz, l(-1.000000, 0.000000, 1.000000, 0.000000)
div r1.xyzw, l(100.000000, 100.000000, 100.000000, 100.000000), cb0[5].zwzw
mad r2.xyzw, r0.yxwz, r1.zwzw, v2.xyxy
mad r0.xyzw, r0.xyzw, r1.xyzw, v2.xyxy
sample r3.xyzw, r2.xyxx, t0.xyzw, s0
sample r2.xyzw, r2.zwzz, t0.xyzw, s0
min r2.x, r2.w, r3.w
sample r3.xyzw, r0.xyxx, t0.xyzw, s0
sample r0.xyzw, r0.zwzz, t0.xyzw, s0
min r0.x, r2.x, r3.w
min r0.x, r0.w, r0.x
mul r2.xyzw, cb0[11].zzzz, l(0.705000, 0.705000, -0.705000, 0.705000)
mad r3.xyzw, r2.xyzw, r1.xyzw, v2.xyxy
mad r1.xyzw, r2.wzzz, r1.xyzw, v2.xyxy
sample r2.xyzw, r3.xyxx, t0.xyzw, s0
sample r3.xyzw, r3.zwzz, t0.xyzw, s0
min r0.x, r0.x, r2.w
min r0.x, r3.w, r0.x
sample r2.xyzw, r1.xyxx, t0.xyzw, s0
sample r1.xyzw, r1.zwzz, t0.xyzw, s0
min r0.x, r0.x, r2.w
min r0.x, r1.w, r0.x
add r0.x, -r0.x, l(1.000000)
mul r0.x, r0.x, cb0[9].z
sample r1.xyzw, v2.xyxx, t0.xyzw, s0
mul r0.y, r0.x, r1.w
mad r0.z, r0.y, v1.w, l(-0.001000)
mul r0.y, r0.y, v1.w
mov o0.w, r0.y
lt r0.y, r0.z, l(0.000000)
discard_nz r0.y
add r0.yzw, -r1.xxyz, cb0[8].xxyz
mad r0.xyz, r0.xxxx, r0.yzwy, r1.xyzx
mul o0.xyz, r0.xyzx, v1.xyzx
ret 
// Approximately 0 instruction slots used
