//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float   xyz 
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// TEXCOORD                 5   xyzw        6     NONE   float   xyz 
// TEXCOORD                 7   xyzw        7     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[11], immediateIndexed
dcl_constantbuffer CB1[47], immediateIndexed
dcl_constantbuffer CB2[8], immediateIndexed
dcl_constantbuffer CB3[7], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texturecube (float,float,float,float) t8
dcl_resource_texturecube (float,float,float,float) t9
dcl_resource_texture3d (float,float,float,float) t10
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyz
dcl_output o0.xyzw
dcl_temps 15
sample r0.xyzw, v1.xyxx, t0.xyzw, s2
mul o0.w, r0.w, cb0[4].w
sample r1.xyzw, v1.xyxx, t1.xyzw, s7
mul r0.xyz, r0.xyzx, cb0[4].xyzx
sample r2.xyzw, v1.xyxx, t2.xyzw, s5
sample r3.xyzw, v1.zwzz, t3.xyzw, s3
mul r2.xyz, r2.wwww, r3.xyzx
add r0.w, -r2.w, l(1.000000)
mad r2.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r0.wwww
mul r3.xyz, r0.xyzx, r2.xyzx
mad r0.xyz, r0.xyzx, r2.xyzx, l(-0.220916, -0.220916, -0.220916, 0.000000)
mad r0.xyz, r1.xxxx, r0.xyzx, l(0.220916, 0.220916, 0.220916, 0.000000)
mad r0.w, -r1.x, l(0.779084), l(0.779084)
mul r1.xyz, r0.wwww, r3.xyzx
sample r3.xyzw, v1.xyxx, t4.xyzw, s4
mul r3.x, r3.w, r3.x
mad r2.xy, r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r3.xy, r2.xyxx, cb0[8].xxxx
dp2 r2.z, r3.xyxx, r3.xyxx
min r2.z, r2.z, l(1.000000)
add r2.z, -r2.z, l(1.000000)
sqrt r3.z, r2.z
sample r4.xyzw, v1.zwzz, t5.xyzw, s6
mul r4.x, r4.w, r4.x
mad r4.xy, r4.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r4.xy, r4.xyxx, cb0[8].yyyy
dp2 r2.z, r4.xyxx, r4.xyxx
min r2.z, r2.z, l(1.000000)
add r2.z, -r2.z, l(1.000000)
sqrt r2.z, r2.z
mad r4.xy, r2.xyxx, cb0[8].xxxx, r4.xyxx
mul r4.z, r2.z, r3.z
dp3 r2.x, r4.xyzx, r4.xyzx
rsq r2.x, r2.x
mad r2.xyz, r4.xyzx, r2.xxxx, -r3.xyzx
mad r2.xyz, r2.wwww, r2.xyzx, r3.xyzx
mul r3.xyz, r2.yyyy, v4.xyzx
mad r2.xyw, v3.xyxz, r2.xxxx, r3.xyxz
mad r2.xyz, v5.xyzx, r2.zzzz, r2.xywx
dp3 r2.w, r2.xyzx, r2.xyzx
rsq r2.w, r2.w
mul r2.xyz, r2.wwww, r2.xyzx
dp3 r3.x, v2.xyzx, v2.xyzx
rsq r3.x, r3.x
mul r3.yzw, r3.xxxx, v2.xxyz
eq r4.x, cb3[0].x, l(1.000000)
if_nz r4.x
  eq r4.y, cb3[0].y, l(1.000000)
  mul r5.xyz, v4.wwww, cb3[2].xyzx
  mad r5.xyz, cb3[1].xyzx, v3.wwww, r5.xyzx
  mad r5.xyz, cb3[3].xyzx, v5.wwww, r5.xyzx
  add r5.xyz, r5.xyzx, cb3[4].xyzx
  mov r6.y, v3.w
  mov r6.z, v4.w
  mov r6.w, v5.w
  movc r4.yzw, r4.yyyy, r5.xxyz, r6.yyzw
  add r4.yzw, r4.yyzw, -cb3[6].xxyz
  mul r5.yzw, r4.yyzw, cb3[5].xxyz
  mad r4.y, r5.y, l(0.250000), l(0.750000)
  mad r4.z, cb3[0].z, l(0.500000), l(0.750000)
  max r5.x, r4.z, r4.y
  sample r5.xyzw, r5.xzwx, t10.xyzw, s1
else 
  mov r5.xyzw, l(1.000000,1.000000,1.000000,1.000000)
endif 
dp4_sat r4.y, r5.xyzw, cb1[46].xyzw
sample r5.xyzw, v1.xyxx, t6.xyzw, s8
add r4.z, -cb0[9].y, l(1.000000)
mad r4.z, r5.y, cb0[9].y, r4.z
mad r4.w, -r1.w, cb0[9].x, l(1.000000)
dp3 r5.x, r3.yzwy, r2.xyzx
add r5.x, r5.x, r5.x
mad r5.xyz, r2.xyzx, -r5.xxxx, r3.yzwy
mul r6.xyz, r4.yyyy, cb0[2].xyzx
if_nz r4.x
  eq r4.x, cb3[0].y, l(1.000000)
  mul r7.xyz, v4.wwww, cb3[2].xyzx
  mad r7.xyz, cb3[1].xyzx, v3.wwww, r7.xyzx
  mad r7.xyz, cb3[3].xyzx, v5.wwww, r7.xyzx
  add r7.xyz, r7.xyzx, cb3[4].xyzx
  mov r8.y, v3.w
  mov r8.z, v4.w
  mov r8.w, v5.w
  movc r7.xyz, r4.xxxx, r7.xyzx, r8.yzwy
  add r7.xyz, r7.xyzx, -cb3[6].xyzx
  mul r7.yzw, r7.xxyz, cb3[5].xxyz
  mul r4.x, r7.y, l(0.250000)
  mul r4.y, cb3[0].z, l(0.500000)
  mad r5.w, -cb3[0].z, l(0.500000), l(0.250000)
  max r4.x, r4.y, r4.x
  min r7.x, r5.w, r4.x
  sample r8.xyzw, r7.xzwx, t10.xyzw, s1
  add r9.xyz, r7.xzwx, l(0.250000, 0.000000, 0.000000, 0.000000)
  sample r9.xyzw, r9.xyzx, t10.xyzw, s1
  add r7.xyz, r7.xzwx, l(0.500000, 0.000000, 0.000000, 0.000000)
  sample r7.xyzw, r7.xyzx, t10.xyzw, s1
  mov r2.w, l(1.000000)
  dp4 r8.x, r8.xyzw, r2.xyzw
  dp4 r8.y, r9.xyzw, r2.xyzw
  dp4 r8.z, r7.xyzw, r2.xyzw
else 
  mov r2.w, l(1.000000)
  dp4 r8.x, cb1[39].xyzw, r2.xyzw
  dp4 r8.y, cb1[40].xyzw, r2.xyzw
  dp4 r8.z, cb1[41].xyzw, r2.xyzw
endif 
add r7.xyz, r8.xyzx, v6.xyzx
max r7.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
log r7.xyz, r7.xyzx
mul r7.xyz, r7.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r7.xyz, r7.xyzx
mad r7.xyz, r7.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
max r7.xyz, r7.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
lt r2.w, l(0.000000), cb2[2].w
if_nz r2.w
  dp3 r2.w, r5.xyzx, r5.xyzx
  rsq r2.w, r2.w
  mul r8.xyz, r2.wwww, r5.xyzx
  mov r9.x, v3.w
  mov r9.y, v4.w
  mov r9.z, v5.w
  add r10.xyz, -r9.xyzx, cb2[0].xyzx
  div r10.xyz, r10.xyzx, r8.xyzx
  add r11.xyz, -r9.xyzx, cb2[1].xyzx
  div r11.xyz, r11.xyzx, r8.xyzx
  lt r12.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r8.xyzx
  movc r10.xyz, r12.xyzx, r10.xyzx, r11.xyzx
  min r2.w, r10.y, r10.x
  min r2.w, r10.z, r2.w
  add r9.xyz, r9.xyzx, -cb2[2].xyzx
  mad r8.xyz, r8.xyzx, r2.wwww, r9.xyzx
else 
  mov r8.xyz, r5.xyzx
endif 
mad r2.w, -r4.w, l(0.700000), l(1.700000)
mul r2.w, r2.w, r4.w
mul r2.w, r2.w, l(6.000000)
sample_l r8.xyzw, r8.xyzx, t8.xyzw, s0, r2.w
add r4.x, r8.w, l(-1.000000)
mad r4.x, cb2[3].w, r4.x, l(1.000000)
mul r4.x, r4.x, cb2[3].x
mul r9.xyz, r8.xyzx, r4.xxxx
lt r4.y, cb2[1].w, l(0.999990)
if_nz r4.y
  lt r4.y, l(0.000000), cb2[6].w
  if_nz r4.y
    dp3 r4.y, r5.xyzx, r5.xyzx
    rsq r4.y, r4.y
    mul r10.xyz, r4.yyyy, r5.xyzx
    mov r11.x, v3.w
    mov r11.y, v4.w
    mov r11.z, v5.w
    add r12.xyz, -r11.xyzx, cb2[4].xyzx
    div r12.xyz, r12.xyzx, r10.xyzx
    add r13.xyz, -r11.xyzx, cb2[5].xyzx
    div r13.xyz, r13.xyzx, r10.xyzx
    lt r14.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r10.xyzx
    movc r12.xyz, r14.xyzx, r12.xyzx, r13.xyzx
    min r4.y, r12.y, r12.x
    min r4.y, r12.z, r4.y
    add r11.xyz, r11.xyzx, -cb2[6].xyzx
    mad r5.xyz, r10.xyzx, r4.yyyy, r11.xyzx
  endif 
  sample_l r5.xyzw, r5.xyzx, t9.xyzw, s0, r2.w
  add r2.w, r5.w, l(-1.000000)
  mad r2.w, cb2[7].w, r2.w, l(1.000000)
  mul r2.w, r2.w, cb2[7].x
  mul r5.xyz, r5.xyzx, r2.wwww
  mad r8.xyz, r4.xxxx, r8.xyzx, -r5.xyzx
  mad r9.xyz, cb2[1].wwww, r8.xyzx, r5.xyzx
endif 
mul r5.xyz, r4.zzzz, r9.xyzx
mad r8.xyz, -v2.xyzx, r3.xxxx, cb1[0].xyzx
dp3 r2.w, r8.xyzx, r8.xyzx
max r2.w, r2.w, l(0.001000)
rsq r2.w, r2.w
mul r8.xyz, r2.wwww, r8.xyzx
dp3 r2.w, r2.xyzx, -r3.yzwy
dp3_sat r3.x, r2.xyzx, cb1[0].xyzx
dp3_sat r2.x, r2.xyzx, r8.xyzx
dp3_sat r2.y, cb1[0].xyzx, r8.xyzx
mul r2.z, r2.y, r2.y
dp2 r2.z, r2.zzzz, r4.wwww
add r2.z, r2.z, l(-0.500000)
add r3.y, -r3.x, l(1.000000)
mul r3.z, r3.y, r3.y
mul r3.z, r3.z, r3.z
mul r3.y, r3.y, r3.z
mad r3.y, r2.z, r3.y, l(1.000000)
add r3.z, -|r2.w|, l(1.000000)
mul r3.w, r3.z, r3.z
mul r3.w, r3.w, r3.w
mul r3.z, r3.z, r3.w
mad r2.z, r2.z, r3.z, l(1.000000)
mul r2.z, r2.z, r3.y
mul r3.y, r4.w, r4.w
max r3.y, r3.y, l(0.002000)
add r3.w, -r3.y, l(1.000000)
mad r4.x, |r2.w|, r3.w, r3.y
mad r3.w, r3.x, r3.w, r3.y
mul r2.w, |r2.w|, r3.w
mad r2.w, r3.x, r4.x, r2.w
add r2.w, r2.w, l(0.000010)
div r2.w, l(0.500000), r2.w
mul r3.w, r3.y, r3.y
mad r4.x, r2.x, r3.w, -r2.x
mad r2.x, r4.x, r2.x, l(1.000000)
mul r3.w, r3.w, l(0.318310)
mad r2.x, r2.x, r2.x, l(0.000000)
div r2.x, r3.w, r2.x
mul r2.x, r2.x, r2.w
mul r2.x, r2.x, l(3.141593)
max r2.x, r2.x, l(0.000100)
sqrt r2.x, r2.x
mul r2.xz, r3.xxxx, r2.xxzx
mul r2.w, r3.y, l(0.280000)
mad r2.w, -r2.w, r4.w, l(1.000000)
dp3 r3.x, r0.xyzx, r0.xyzx
ne r3.x, r3.x, l(0.000000)
and r3.x, r3.x, l(0x3f800000)
mul r2.x, r2.x, r3.x
mad r0.w, r1.w, cb0[9].x, -r0.w
add_sat r0.w, r0.w, l(1.000000)
mul r3.xyw, r2.zzzz, r6.xyxz
mad r3.xyw, r7.xyxz, r4.zzzz, r3.xyxw
mul r4.xyz, r6.xyzx, r2.xxxx
add r1.w, -r2.y, l(1.000000)
mul r2.x, r1.w, r1.w
mul r2.x, r2.x, r2.x
mul r1.w, r1.w, r2.x
add r2.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r2.xyz, r2.xyzx, r1.wwww, r0.xyzx
mul r2.xyz, r2.xyzx, r4.xyzx
mad r1.xyz, r1.xyzx, r3.xywx, r2.xyzx
mul r2.xyz, r5.xyzx, r2.wwww
add r3.xyw, -r0.xyxz, r0.wwww
mad r0.xyz, r3.zzzz, r3.xywx, r0.xyzx
mad r0.xyz, r2.xyzx, r0.xyzx, r1.xyzx
sample r1.xyzw, v1.xyxx, t7.xyzw, s9
mad o0.xyz, r1.xyzx, cb0[10].xyzx, r0.xyzx
ret 
// Approximately 0 instruction slots used
