//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float   xyz 
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// TEXCOORD                 5   xyzw        6     NONE   float       
// TEXCOORD                 7   xyzw        7     NONE   float   xy w
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[11], immediateIndexed
dcl_constantbuffer CB1[5], immediateIndexed
dcl_constantbuffer CB2[47], immediateIndexed
dcl_constantbuffer CB3[26], immediateIndexed
dcl_constantbuffer CB4[12], immediateIndexed
dcl_constantbuffer CB5[8], immediateIndexed
dcl_constantbuffer CB6[7], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texturecube (float,float,float,float) t9
dcl_resource_texturecube (float,float,float,float) t10
dcl_resource_texture3d (float,float,float,float) t11
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v7.xyw
dcl_output o0.xyzw
dcl_temps 13
sample r0.xyzw, v1.xyxx, t0.xyzw, s2
mul o0.w, r0.w, cb0[4].w
sample r1.xyzw, v1.xyxx, t1.xyzw, s7
mul r0.xyz, r0.xyzx, cb0[4].xyzx
sample r2.xyzw, v1.xyxx, t2.xyzw, s5
sample r3.xyzw, v1.zwzz, t3.xyzw, s3
mul r2.xyz, r2.wwww, r3.xyzx
add r0.w, -r2.w, l(1.000000)
mad r2.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r0.wwww
mul r3.xyz, r0.xyzx, r2.xyzx
mad r0.xyz, r0.xyzx, r2.xyzx, l(-0.220916, -0.220916, -0.220916, 0.000000)
mad r0.xyz, r1.xxxx, r0.xyzx, l(0.220916, 0.220916, 0.220916, 0.000000)
mad r0.w, -r1.x, l(0.779084), l(0.779084)
mul r1.xyz, r0.wwww, r3.xyzx
sample r3.xyzw, v1.xyxx, t4.xyzw, s4
mul r3.x, r3.w, r3.x
mad r2.xy, r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r3.xy, r2.xyxx, cb0[8].xxxx
dp2 r2.z, r3.xyxx, r3.xyxx
min r2.z, r2.z, l(1.000000)
add r2.z, -r2.z, l(1.000000)
sqrt r3.z, r2.z
sample r4.xyzw, v1.zwzz, t5.xyzw, s6
mul r4.x, r4.w, r4.x
mad r4.xy, r4.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r4.xy, r4.xyxx, cb0[8].yyyy
dp2 r2.z, r4.xyxx, r4.xyxx
min r2.z, r2.z, l(1.000000)
add r2.z, -r2.z, l(1.000000)
sqrt r2.z, r2.z
mad r4.xy, r2.xyxx, cb0[8].xxxx, r4.xyxx
mul r4.z, r2.z, r3.z
dp3 r2.x, r4.xyzx, r4.xyzx
rsq r2.x, r2.x
mad r2.xyz, r4.xyzx, r2.xxxx, -r3.xyzx
mad r2.xyz, r2.wwww, r2.xyzx, r3.xyzx
mul r3.xyz, r2.yyyy, v4.xyzx
mad r2.xyw, v3.xyxz, r2.xxxx, r3.xyxz
mad r2.xyz, v5.xyzx, r2.zzzz, r2.xywx
dp3 r2.w, r2.xyzx, r2.xyzx
rsq r2.w, r2.w
mul r2.xyz, r2.wwww, r2.xyzx
dp3 r2.w, v2.xyzx, v2.xyzx
rsq r2.w, r2.w
mul r3.xyz, r2.wwww, v2.xyzx
mov r4.x, v3.w
mov r4.y, v4.w
mov r4.z, v5.w
add r5.xyz, -r4.xyzx, cb1[4].xyzx
mov r6.x, cb4[9].z
mov r6.y, cb4[10].z
mov r6.z, cb4[11].z
dp3 r3.w, r5.xyzx, r6.xyzx
add r5.xyz, r4.xyzx, -cb3[25].xyzx
dp3 r4.w, r5.xyzx, r5.xyzx
sqrt r4.w, r4.w
add r4.w, -r3.w, r4.w
mad r3.w, cb3[25].w, r4.w, r3.w
mad_sat r3.w, r3.w, cb3[24].z, cb3[24].w
eq r4.w, cb6[0].x, l(1.000000)
if_nz r4.w
  eq r4.w, cb6[0].y, l(1.000000)
  mul r5.xyz, v4.wwww, cb6[2].xyzx
  mad r5.xyz, cb6[1].xyzx, v3.wwww, r5.xyzx
  mad r5.xyz, cb6[3].xyzx, v5.wwww, r5.xyzx
  add r5.xyz, r5.xyzx, cb6[4].xyzx
  movc r5.xyz, r4.wwww, r5.xyzx, r4.xyzx
  add r5.xyz, r5.xyzx, -cb6[6].xyzx
  mul r5.yzw, r5.xxyz, cb6[5].xxyz
  mad r4.w, r5.y, l(0.250000), l(0.750000)
  mad r5.y, cb6[0].z, l(0.500000), l(0.750000)
  max r5.x, r4.w, r5.y
  sample r5.xyzw, r5.xzwx, t11.xyzw, s1
else 
  mov r5.xyzw, l(1.000000,1.000000,1.000000,1.000000)
endif 
dp4_sat r4.w, r5.xyzw, cb2[46].xyzw
div r5.xy, v7.xyxx, v7.wwww
sample r5.xyzw, r5.xyxx, t6.xyzw, s10
add r4.w, r4.w, -r5.x
mad r3.w, r3.w, r4.w, r5.x
sample r5.xyzw, v1.xyxx, t7.xyzw, s8
add r4.w, -cb0[9].y, l(1.000000)
mad r4.w, r5.y, cb0[9].y, r4.w
mad r5.x, -r1.w, cb0[9].x, l(1.000000)
dp3 r5.y, r3.xyzx, r2.xyzx
add r5.y, r5.y, r5.y
mad r5.yzw, r2.xxyz, -r5.yyyy, r3.xxyz
mul r6.xyz, r3.wwww, cb0[2].xyzx
lt r3.w, l(0.000000), cb5[2].w
if_nz r3.w
  dp3 r3.w, r5.yzwy, r5.yzwy
  rsq r3.w, r3.w
  mul r7.xyz, r3.wwww, r5.yzwy
  add r8.xyz, -r4.xyzx, cb5[0].xyzx
  div r8.xyz, r8.xyzx, r7.xyzx
  add r9.xyz, -r4.xyzx, cb5[1].xyzx
  div r9.xyz, r9.xyzx, r7.xyzx
  lt r10.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r7.xyzx
  movc r8.xyz, r10.xyzx, r8.xyzx, r9.xyzx
  min r3.w, r8.y, r8.x
  min r3.w, r8.z, r3.w
  add r8.xyz, r4.xyzx, -cb5[2].xyzx
  mad r7.xyz, r7.xyzx, r3.wwww, r8.xyzx
else 
  mov r7.xyz, r5.yzwy
endif 
mad r3.w, -r5.x, l(0.700000), l(1.700000)
mul r3.w, r3.w, r5.x
mul r3.w, r3.w, l(6.000000)
sample_l r7.xyzw, r7.xyzx, t9.xyzw, s0, r3.w
add r6.w, r7.w, l(-1.000000)
mad r6.w, cb5[3].w, r6.w, l(1.000000)
mul r6.w, r6.w, cb5[3].x
mul r8.xyz, r7.xyzx, r6.wwww
lt r7.w, cb5[1].w, l(0.999990)
if_nz r7.w
  lt r7.w, l(0.000000), cb5[6].w
  if_nz r7.w
    dp3 r7.w, r5.yzwy, r5.yzwy
    rsq r7.w, r7.w
    mul r9.xyz, r5.yzwy, r7.wwww
    add r10.xyz, -r4.xyzx, cb5[4].xyzx
    div r10.xyz, r10.xyzx, r9.xyzx
    add r11.xyz, -r4.xyzx, cb5[5].xyzx
    div r11.xyz, r11.xyzx, r9.xyzx
    lt r12.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r9.xyzx
    movc r10.xyz, r12.xyzx, r10.xyzx, r11.xyzx
    min r7.w, r10.y, r10.x
    min r7.w, r10.z, r7.w
    add r4.xyz, r4.xyzx, -cb5[6].xyzx
    mad r5.yzw, r9.xxyz, r7.wwww, r4.xxyz
  endif 
  sample_l r9.xyzw, r5.yzwy, t10.xyzw, s0, r3.w
  add r3.w, r9.w, l(-1.000000)
  mad r3.w, cb5[7].w, r3.w, l(1.000000)
  mul r3.w, r3.w, cb5[7].x
  mul r4.xyz, r9.xyzx, r3.wwww
  mad r5.yzw, r6.wwww, r7.xxyz, -r4.xxyz
  mad r8.xyz, cb5[1].wwww, r5.yzwy, r4.xyzx
endif 
mul r4.xyz, r4.wwww, r8.xyzx
mad r5.yzw, -v2.xxyz, r2.wwww, cb2[0].xxyz
dp3 r2.w, r5.yzwy, r5.yzwy
max r2.w, r2.w, l(0.001000)
rsq r2.w, r2.w
mul r5.yzw, r2.wwww, r5.yyzw
dp3 r2.w, r2.xyzx, -r3.xyzx
dp3_sat r3.x, r2.xyzx, cb2[0].xyzx
dp3_sat r2.x, r2.xyzx, r5.yzwy
dp3_sat r2.y, cb2[0].xyzx, r5.yzwy
mul r2.z, r2.y, r2.y
dp2 r2.z, r2.zzzz, r5.xxxx
add r2.z, r2.z, l(-0.500000)
add r3.y, -r3.x, l(1.000000)
mul r3.z, r3.y, r3.y
mul r3.z, r3.z, r3.z
mul r3.y, r3.y, r3.z
mad r3.y, r2.z, r3.y, l(1.000000)
add r3.z, -|r2.w|, l(1.000000)
mul r3.w, r3.z, r3.z
mul r3.w, r3.w, r3.w
mul r3.z, r3.z, r3.w
mad r2.z, r2.z, r3.z, l(1.000000)
mul r2.z, r2.z, r3.y
mul r3.y, r5.x, r5.x
max r3.y, r3.y, l(0.002000)
add r3.w, -r3.y, l(1.000000)
mad r4.w, |r2.w|, r3.w, r3.y
mad r3.w, r3.x, r3.w, r3.y
mul r2.w, |r2.w|, r3.w
mad r2.w, r3.x, r4.w, r2.w
add r2.w, r2.w, l(0.000010)
div r2.w, l(0.500000), r2.w
mul r3.w, r3.y, r3.y
mad r4.w, r2.x, r3.w, -r2.x
mad r2.x, r4.w, r2.x, l(1.000000)
mul r3.w, r3.w, l(0.318310)
mad r2.x, r2.x, r2.x, l(0.000000)
div r2.x, r3.w, r2.x
mul r2.x, r2.x, r2.w
mul r2.x, r2.x, l(3.141593)
max r2.x, r2.x, l(0.000100)
sqrt r2.x, r2.x
mul r2.xz, r3.xxxx, r2.xxzx
mul r2.w, r3.y, l(0.280000)
mad r2.w, -r2.w, r5.x, l(1.000000)
dp3 r3.x, r0.xyzx, r0.xyzx
ne r3.x, r3.x, l(0.000000)
and r3.x, r3.x, l(0x3f800000)
mul r2.x, r2.x, r3.x
mad r0.w, r1.w, cb0[9].x, -r0.w
add_sat r0.w, r0.w, l(1.000000)
mul r3.xyw, r2.zzzz, r6.xyxz
mul r5.xyz, r6.xyzx, r2.xxxx
add r1.w, -r2.y, l(1.000000)
mul r2.x, r1.w, r1.w
mul r2.x, r2.x, r2.x
mul r1.w, r1.w, r2.x
add r2.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r2.xyz, r2.xyzx, r1.wwww, r0.xyzx
mul r2.xyz, r2.xyzx, r5.xyzx
mad r1.xyz, r1.xyzx, r3.xywx, r2.xyzx
mul r2.xyz, r4.xyzx, r2.wwww
add r3.xyw, -r0.xyxz, r0.wwww
mad r0.xyz, r3.zzzz, r3.xywx, r0.xyzx
mad r0.xyz, r2.xyzx, r0.xyzx, r1.xyzx
sample r1.xyzw, v1.xyxx, t8.xyzw, s9
mad o0.xyz, r1.xyzx, cb0[10].xyzx, r0.xyzx
ret 
// Approximately 0 instruction slots used
