//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
// TEXCOORD                 1   xy          3     NONE   float   xy  
// TANGENT                  0   xyzw        4     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// TEXCOORD                 5   xyzw        6     NONE   float   xyzw
// TEXCOORD                 7   xyzw        7     NONE   float   xyzw
//
vs_4_0
dcl_constantbuffer CB0[10], immediateIndexed
dcl_constantbuffer CB1[5], immediateIndexed
dcl_constantbuffer CB2[46], immediateIndexed
dcl_constantbuffer CB3[10], immediateIndexed
dcl_constantbuffer CB4[21], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_input v2.xy
dcl_input v3.xy
dcl_input v4.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_output o5.xyzw
dcl_output o6.xyzw
dcl_output o7.xyzw
dcl_temps 3
mul r0.xyzw, v0.yyyy, cb3[1].xyzw
mad r0.xyzw, cb3[0].xyzw, v0.xxxx, r0.xyzw
mad r0.xyzw, cb3[2].xyzw, v0.zzzz, r0.xyzw
add r0.xyzw, r0.xyzw, cb3[3].xyzw
mul r1.xyzw, r0.yyyy, cb4[18].xyzw
mad r1.xyzw, cb4[17].xyzw, r0.xxxx, r1.xyzw
mad r1.xyzw, cb4[19].xyzw, r0.zzzz, r1.xyzw
mad o0.xyzw, cb4[20].xyzw, r0.wwww, r1.xyzw
eq r0.x, cb0[9].w, l(0.000000)
movc r0.xy, r0.xxxx, v2.xyxx, v3.xyxx
mad o1.zw, r0.xxxy, cb0[7].xxxy, cb0[7].zzzw
mad o1.xy, v2.xyxx, cb0[6].xyxx, cb0[6].zwzz
mov o2.w, l(0)
mul r0.xyz, v0.yyyy, cb3[1].xyzx
mad r0.xyz, cb3[0].xyzx, v0.xxxx, r0.xyzx
mad r0.xyz, cb3[2].xyzx, v0.zzzz, r0.xyzx
mad r0.xyz, cb3[3].xyzx, v0.wwww, r0.xyzx
add o2.xyz, r0.xyzx, -cb1[4].xyzx
mov o3.w, r0.x
mul r1.xyz, v4.yyyy, cb3[1].xyzx
mad r1.xyz, cb3[0].xyzx, v4.xxxx, r1.xyzx
mad r1.xyz, cb3[2].xyzx, v4.zzzz, r1.xyzx
dp3 r0.x, r1.xyzx, r1.xyzx
rsq r0.x, r0.x
mul r1.xyz, r0.xxxx, r1.xyzx
mov o3.xyz, r1.xyzx
mov o4.w, r0.y
mov o5.w, r0.z
dp3 r0.x, v1.xyzx, cb3[4].xyzx
dp3 r0.y, v1.xyzx, cb3[5].xyzx
dp3 r0.z, v1.xyzx, cb3[6].xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx
mul r2.xyz, r1.yzxy, r0.zxyz
mad r1.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
mul r0.w, v4.w, cb3[9].w
mul o4.xyz, r0.wwww, r1.xyzx
mov o5.xyz, r0.xyzx
mul r0.w, r0.y, r0.y
mad r0.w, r0.x, r0.x, -r0.w
mul r1.xyzw, r0.yzzx, r0.xyzz
dp4 r0.x, cb2[42].xyzw, r1.xyzw
dp4 r0.y, cb2[43].xyzw, r1.xyzw
dp4 r0.z, cb2[44].xyzw, r1.xyzw
mad o6.xyz, cb2[45].xyzx, r0.wwww, r0.xyzx
mov o6.w, l(0)
mov o7.xyzw, l(0,0,0,0)
ret 
// Approximately 0 instruction slots used
