//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float   xyz 
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
// TEXCOORD                 3   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// TEXCOORD                 5   xyzw        6     NONE   float   xyz 
// TEXCOORD                 7   xyzw        7     NONE   float   xy w
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[11], immediateIndexed
dcl_constantbuffer CB1[5], immediateIndexed
dcl_constantbuffer CB2[47], immediateIndexed
dcl_constantbuffer CB3[26], immediateIndexed
dcl_constantbuffer CB4[12], immediateIndexed
dcl_constantbuffer CB5[8], immediateIndexed
dcl_constantbuffer CB6[7], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_sampler s4, mode_default
dcl_sampler s5, mode_default
dcl_sampler s6, mode_default
dcl_sampler s7, mode_default
dcl_sampler s8, mode_default
dcl_sampler s9, mode_default
dcl_sampler s10, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texturecube (float,float,float,float) t9
dcl_resource_texturecube (float,float,float,float) t10
dcl_resource_texture3d (float,float,float,float) t11
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyzw
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyzw
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.xyw
dcl_output o0.xyzw
dcl_temps 15
sample r0.xyzw, v1.xyxx, t0.xyzw, s2
mul o0.w, r0.w, cb0[4].w
sample r1.xyzw, v1.xyxx, t1.xyzw, s7
mul r0.xyz, r0.xyzx, cb0[4].xyzx
sample r2.xyzw, v1.xyxx, t2.xyzw, s5
sample r3.xyzw, v1.zwzz, t3.xyzw, s3
mul r2.xyz, r2.wwww, r3.xyzx
add r0.w, -r2.w, l(1.000000)
mad r2.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r0.wwww
mul r3.xyz, r0.xyzx, r2.xyzx
mad r0.xyz, r0.xyzx, r2.xyzx, l(-0.220916, -0.220916, -0.220916, 0.000000)
mad r0.xyz, r1.xxxx, r0.xyzx, l(0.220916, 0.220916, 0.220916, 0.000000)
mad r0.w, -r1.x, l(0.779084), l(0.779084)
mul r1.xyz, r0.wwww, r3.xyzx
sample r3.xyzw, v1.xyxx, t4.xyzw, s4
mul r3.x, r3.w, r3.x
mad r2.xy, r3.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r3.xy, r2.xyxx, cb0[8].xxxx
dp2 r2.z, r3.xyxx, r3.xyxx
min r2.z, r2.z, l(1.000000)
add r2.z, -r2.z, l(1.000000)
sqrt r3.z, r2.z
sample r4.xyzw, v1.zwzz, t5.xyzw, s6
mul r4.x, r4.w, r4.x
mad r4.xy, r4.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r4.xy, r4.xyxx, cb0[8].yyyy
dp2 r2.z, r4.xyxx, r4.xyxx
min r2.z, r2.z, l(1.000000)
add r2.z, -r2.z, l(1.000000)
sqrt r2.z, r2.z
mad r4.xy, r2.xyxx, cb0[8].xxxx, r4.xyxx
mul r4.z, r2.z, r3.z
dp3 r2.x, r4.xyzx, r4.xyzx
rsq r2.x, r2.x
mad r2.xyz, r4.xyzx, r2.xxxx, -r3.xyzx
mad r2.xyz, r2.wwww, r2.xyzx, r3.xyzx
mul r3.xyz, r2.yyyy, v4.xyzx
mad r2.xyw, v3.xyxz, r2.xxxx, r3.xyxz
mad r2.xyz, v5.xyzx, r2.zzzz, r2.xywx
dp3 r2.w, r2.xyzx, r2.xyzx
rsq r2.w, r2.w
mul r2.xyz, r2.wwww, r2.xyzx
dp3 r3.x, v2.xyzx, v2.xyzx
rsq r3.x, r3.x
mul r3.yzw, r3.xxxx, v2.xxyz
mov r4.x, v3.w
mov r4.y, v4.w
mov r4.z, v5.w
add r5.xyz, -r4.xyzx, cb1[4].xyzx
mov r6.x, cb4[9].z
mov r6.y, cb4[10].z
mov r6.z, cb4[11].z
dp3 r4.w, r5.xyzx, r6.xyzx
add r5.xyz, r4.xyzx, -cb3[25].xyzx
dp3 r5.x, r5.xyzx, r5.xyzx
sqrt r5.x, r5.x
add r5.x, -r4.w, r5.x
mad r4.w, cb3[25].w, r5.x, r4.w
mad_sat r4.w, r4.w, cb3[24].z, cb3[24].w
eq r5.x, cb6[0].x, l(1.000000)
if_nz r5.x
  eq r5.y, cb6[0].y, l(1.000000)
  mul r6.xyz, v4.wwww, cb6[2].xyzx
  mad r6.xyz, cb6[1].xyzx, v3.wwww, r6.xyzx
  mad r6.xyz, cb6[3].xyzx, v5.wwww, r6.xyzx
  add r6.xyz, r6.xyzx, cb6[4].xyzx
  movc r5.yzw, r5.yyyy, r6.xxyz, r4.xxyz
  add r5.yzw, r5.yyzw, -cb6[6].xxyz
  mul r6.yzw, r5.yyzw, cb6[5].xxyz
  mad r5.y, r6.y, l(0.250000), l(0.750000)
  mad r5.z, cb6[0].z, l(0.500000), l(0.750000)
  max r6.x, r5.z, r5.y
  sample r6.xyzw, r6.xzwx, t11.xyzw, s1
else 
  mov r6.xyzw, l(1.000000,1.000000,1.000000,1.000000)
endif 
dp4_sat r5.y, r6.xyzw, cb2[46].xyzw
div r5.zw, v7.xxxy, v7.wwww
sample r6.xyzw, r5.zwzz, t6.xyzw, s10
add r5.y, r5.y, -r6.x
mad r4.w, r4.w, r5.y, r6.x
sample r6.xyzw, v1.xyxx, t7.xyzw, s8
add r5.y, -cb0[9].y, l(1.000000)
mad r5.y, r6.y, cb0[9].y, r5.y
mad r5.z, -r1.w, cb0[9].x, l(1.000000)
dp3 r5.w, r3.yzwy, r2.xyzx
add r5.w, r5.w, r5.w
mad r6.xyz, r2.xyzx, -r5.wwww, r3.yzwy
mul r7.xyz, r4.wwww, cb0[2].xyzx
if_nz r5.x
  eq r4.w, cb6[0].y, l(1.000000)
  mul r8.xyz, v4.wwww, cb6[2].xyzx
  mad r8.xyz, cb6[1].xyzx, v3.wwww, r8.xyzx
  mad r8.xyz, cb6[3].xyzx, v5.wwww, r8.xyzx
  add r8.xyz, r8.xyzx, cb6[4].xyzx
  movc r8.xyz, r4.wwww, r8.xyzx, r4.xyzx
  add r8.xyz, r8.xyzx, -cb6[6].xyzx
  mul r8.yzw, r8.xxyz, cb6[5].xxyz
  mul r4.w, r8.y, l(0.250000)
  mul r5.x, cb6[0].z, l(0.500000)
  mad r5.w, -cb6[0].z, l(0.500000), l(0.250000)
  max r4.w, r4.w, r5.x
  min r8.x, r5.w, r4.w
  sample r9.xyzw, r8.xzwx, t11.xyzw, s1
  add r10.xyz, r8.xzwx, l(0.250000, 0.000000, 0.000000, 0.000000)
  sample r10.xyzw, r10.xyzx, t11.xyzw, s1
  add r8.xyz, r8.xzwx, l(0.500000, 0.000000, 0.000000, 0.000000)
  sample r8.xyzw, r8.xyzx, t11.xyzw, s1
  mov r2.w, l(1.000000)
  dp4 r9.x, r9.xyzw, r2.xyzw
  dp4 r9.y, r10.xyzw, r2.xyzw
  dp4 r9.z, r8.xyzw, r2.xyzw
else 
  mov r2.w, l(1.000000)
  dp4 r9.x, cb2[39].xyzw, r2.xyzw
  dp4 r9.y, cb2[40].xyzw, r2.xyzw
  dp4 r9.z, cb2[41].xyzw, r2.xyzw
endif 
add r8.xyz, r9.xyzx, v6.xyzx
max r8.xyz, r8.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
log r8.xyz, r8.xyzx
mul r8.xyz, r8.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
exp r8.xyz, r8.xyzx
mad r8.xyz, r8.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
max r8.xyz, r8.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
lt r2.w, l(0.000000), cb5[2].w
if_nz r2.w
  dp3 r2.w, r6.xyzx, r6.xyzx
  rsq r2.w, r2.w
  mul r9.xyz, r2.wwww, r6.xyzx
  add r10.xyz, -r4.xyzx, cb5[0].xyzx
  div r10.xyz, r10.xyzx, r9.xyzx
  add r11.xyz, -r4.xyzx, cb5[1].xyzx
  div r11.xyz, r11.xyzx, r9.xyzx
  lt r12.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r9.xyzx
  movc r10.xyz, r12.xyzx, r10.xyzx, r11.xyzx
  min r2.w, r10.y, r10.x
  min r2.w, r10.z, r2.w
  add r10.xyz, r4.xyzx, -cb5[2].xyzx
  mad r9.xyz, r9.xyzx, r2.wwww, r10.xyzx
else 
  mov r9.xyz, r6.xyzx
endif 
mad r2.w, -r5.z, l(0.700000), l(1.700000)
mul r2.w, r2.w, r5.z
mul r2.w, r2.w, l(6.000000)
sample_l r9.xyzw, r9.xyzx, t9.xyzw, s0, r2.w
add r4.w, r9.w, l(-1.000000)
mad r4.w, cb5[3].w, r4.w, l(1.000000)
mul r4.w, r4.w, cb5[3].x
mul r10.xyz, r9.xyzx, r4.wwww
lt r5.x, cb5[1].w, l(0.999990)
if_nz r5.x
  lt r5.x, l(0.000000), cb5[6].w
  if_nz r5.x
    dp3 r5.x, r6.xyzx, r6.xyzx
    rsq r5.x, r5.x
    mul r11.xyz, r5.xxxx, r6.xyzx
    add r12.xyz, -r4.xyzx, cb5[4].xyzx
    div r12.xyz, r12.xyzx, r11.xyzx
    add r13.xyz, -r4.xyzx, cb5[5].xyzx
    div r13.xyz, r13.xyzx, r11.xyzx
    lt r14.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r11.xyzx
    movc r12.xyz, r14.xyzx, r12.xyzx, r13.xyzx
    min r5.x, r12.y, r12.x
    min r5.x, r12.z, r5.x
    add r4.xyz, r4.xyzx, -cb5[6].xyzx
    mad r6.xyz, r11.xyzx, r5.xxxx, r4.xyzx
  endif 
  sample_l r6.xyzw, r6.xyzx, t10.xyzw, s0, r2.w
  add r2.w, r6.w, l(-1.000000)
  mad r2.w, cb5[7].w, r2.w, l(1.000000)
  mul r2.w, r2.w, cb5[7].x
  mul r4.xyz, r6.xyzx, r2.wwww
  mad r6.xyz, r4.wwww, r9.xyzx, -r4.xyzx
  mad r10.xyz, cb5[1].wwww, r6.xyzx, r4.xyzx
endif 
mul r4.xyz, r5.yyyy, r10.xyzx
mad r6.xyz, -v2.xyzx, r3.xxxx, cb2[0].xyzx
dp3 r2.w, r6.xyzx, r6.xyzx
max r2.w, r2.w, l(0.001000)
rsq r2.w, r2.w
mul r6.xyz, r2.wwww, r6.xyzx
dp3 r2.w, r2.xyzx, -r3.yzwy
dp3_sat r3.x, r2.xyzx, cb2[0].xyzx
dp3_sat r2.x, r2.xyzx, r6.xyzx
dp3_sat r2.y, cb2[0].xyzx, r6.xyzx
mul r2.z, r2.y, r2.y
dp2 r2.z, r2.zzzz, r5.zzzz
add r2.z, r2.z, l(-0.500000)
add r3.y, -r3.x, l(1.000000)
mul r3.z, r3.y, r3.y
mul r3.z, r3.z, r3.z
mul r3.y, r3.y, r3.z
mad r3.y, r2.z, r3.y, l(1.000000)
add r3.z, -|r2.w|, l(1.000000)
mul r3.w, r3.z, r3.z
mul r3.w, r3.w, r3.w
mul r3.z, r3.z, r3.w
mad r2.z, r2.z, r3.z, l(1.000000)
mul r2.z, r2.z, r3.y
mul r3.y, r5.z, r5.z
max r3.y, r3.y, l(0.002000)
add r3.w, -r3.y, l(1.000000)
mad r4.w, |r2.w|, r3.w, r3.y
mad r3.w, r3.x, r3.w, r3.y
mul r2.w, |r2.w|, r3.w
mad r2.w, r3.x, r4.w, r2.w
add r2.w, r2.w, l(0.000010)
div r2.w, l(0.500000), r2.w
mul r3.w, r3.y, r3.y
mad r4.w, r2.x, r3.w, -r2.x
mad r2.x, r4.w, r2.x, l(1.000000)
mul r3.w, r3.w, l(0.318310)
mad r2.x, r2.x, r2.x, l(0.000000)
div r2.x, r3.w, r2.x
mul r2.x, r2.x, r2.w
mul r2.x, r2.x, l(3.141593)
max r2.x, r2.x, l(0.000100)
sqrt r2.x, r2.x
mul r2.xz, r3.xxxx, r2.xxzx
mul r2.w, r3.y, l(0.280000)
mad r2.w, -r2.w, r5.z, l(1.000000)
dp3 r3.x, r0.xyzx, r0.xyzx
ne r3.x, r3.x, l(0.000000)
and r3.x, r3.x, l(0x3f800000)
mul r2.x, r2.x, r3.x
mad r0.w, r1.w, cb0[9].x, -r0.w
add_sat r0.w, r0.w, l(1.000000)
mul r3.xyw, r2.zzzz, r7.xyxz
mad r3.xyw, r8.xyxz, r5.yyyy, r3.xyxw
mul r5.xyz, r7.xyzx, r2.xxxx
add r1.w, -r2.y, l(1.000000)
mul r2.x, r1.w, r1.w
mul r2.x, r2.x, r2.x
mul r1.w, r1.w, r2.x
add r2.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r2.xyz, r2.xyzx, r1.wwww, r0.xyzx
mul r2.xyz, r2.xyzx, r5.xyzx
mad r1.xyz, r1.xyzx, r3.xywx, r2.xyzx
mul r2.xyz, r4.xyzx, r2.wwww
add r3.xyw, -r0.xyxz, r0.wwww
mad r0.xyz, r3.zzzz, r3.xywx, r0.xyzx
mad r0.xyz, r2.xyzx, r0.xyzx, r1.xyzx
sample r1.xyzw, v1.xyxx, t8.xyzw, s9
mad o0.xyz, r1.xyzx, cb0[10].xyzx, r0.xyzx
ret 
// Approximately 0 instruction slots used
